### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by zenglongjin** [reimandlab/RM2#2] opened 2021-10-30 11:46 UTC
Dear Reimand:
After we add the final 16834 line: chr3 12146056 12147096 (previous 16833 lines did not report an error), we got a strange message as following:
`Error in RM2(maf = muts, sites = ctcf_chr3_4, window_size = window_size) : 
  Error in .width_as_unnamed_integer(width, msg = "an end that is greater or equal to its start minus one") : 
  each range must have an end that is greater
  or equal to its start minus one`

Thank you very much for your attention and consideration.
<meta name="ctcf_chr3_4">
             chr | start      | end
1         chr1 | 843081 | 843977
...
16833 chr3 | 12138282 | 12139593
16834 chr3 | 12146056 | 12147096**

**Comment by reimand0** [comment] 2021-10-30 13:38
Hi Zenglongjin,
thanks for reporting. I was not able to reproduce this error by adding that
last site to the sites shown in the example on my github (object
ctcf_chr3_4).

 ctcf_chr3_4 = rbind(ctcf_chr3_4, data.frame(chr="chr3", start=12146056,
end=12147096, stringsAsFactors= FALSE))
window_size = 25
results2 = RM2(maf = muts, sites = ctcf_chr3_4, window_size = window_size)
results2
#                mut_type           pp this_coef obs_mut exp_mut exp_mut_lo
#1 total_muts__total_muts 9.175249e-11 0.5609654     274     199        172
#  exp_mut_hi       fc pp_cofac this_coef_cofac n_sites_tested
# 1        227 1.376884       NA              NA           7195

One potential solution: perhaps there is another site in your dataset that
duplicates the region chr3:12146056-12147096 or overlaps it partially,
causing this error. In RM2, site midpoints are derived, then the sites are
extended in both directions by fixed sequence length, and then all sites
are merged.

I hope this helps!

Jüri

**Comment by zenglongjin** [comment] 2021-10-30 14:17
Dear Reimand:
After testing it, I found that mutational data had duplicate fragments, along with an new error that prevented the package from running smoothly when doing function: _cbind(mutations_chr3_4,get_mut_trinuc_strand(mutations_chr3_4))_. 
The error as following:
`Error in loadFUN(x, seqname, ranges) : trying to load regions beyond the
  boundaries of non-circular sequence "chr5"`
Thank you very much for your attention and consideration.

**Comment by reimand0** [comment] 2021-10-30 14:59
OK, this makes sense. One of the sites or mutations is very close to the
end of Chr5. Sometimes this could happen when GRCH38 and GRCH37 are mixed
up.

**Comment by zenglongjin** [comment] 2021-10-30 15:20
Dear Reimand:
Your suggestion is helpful, while we noticed the NCBI_Build=='GRCH38' in mutational data downloaded by TCGAbiolinks-mutect2 pipeline. We don't know how to discern the accuracy of TCGAbiolinks, perhaps further improvements are necessary.
Thank you very much for your attention and consideration.

**Comment by reimand0** [comment] 2021-10-31 15:43
ok, I'm glad it helped. I will close this issue now. Please feel free to get in touch again.

**Closed as completed by reimand0** 2021-10-31 15:43 UTC
